name: Python Tests
on:
  pull_request:
    branches: [ main ]
    paths: ['*.py', 'requirements.txt']

jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.8, 3.9, 3.10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and capture output
        id: pytest
        run: |
            pytest --maxfail=1 --disable-warnings -q > pytest-output.txt
      
      - name: Create PR comment with test result
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Pytest Results**
            ```
            ${{ steps.pytest.outputs.stdout }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  